name: Prevent Merge to Development

on:
    pull_request:
        types:
            - synchronize
            - opened
            - reopened

jobs:
    prevent_merge:
        runs-on: ubuntu-latest

        steps:
            -   name: Check for approved pull request
                id: check_pr
                run: |
                    PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master&head=development" \
                      | jq '.[] | .number')
                    IS_PR_APPROVED=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/${{ PR_NUMBER }}/reviews" \
                      | jq 'any(select(.state == "APPROVED"))')
                    if [ "$IS_PR_APPROVED" = true ]; then
                      echo "There is already an approved pull request from development to master. Merging into development is not allowed."
                      exit 1
                    fi
