name: Prevent Merge to Development

on:
    pull_request:
        types:
            - synchronize
            - opened
            - reopened

jobs:
    prevent_merge:
        runs-on: ubuntu-latest

        steps:
            -   name: Check for approved pull request
                id: check_pr
                run: |
                    APPROVED_PR=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=master&head=development" \
                      | jq '.[] | select(.state == "APPROVED")')
                    if [[ -n "$APPROVED_PR" ]]; then
                      echo "There is already an approved pull request from development to master. Merging into development is not allowed."
                      exit 1
                    fi
